### ISSUE TITLE
Error handling - user not registered in Developer Dashboard

### ISSUE THREAD

**Issue by larryhudson** [larryhudson/spotify-merge-playlist#14]
I think a few people have been getting this error and giving up. But currently my error handling isn't good enough. It gets to the point where it's parsing the JSON of the response when it's looking up the playlist:

```
Dec 23, 02:35:04 PM: info   SyntaxError: Unexpected token 'U', "User not r"... is not valid JSON
Dec 23, 02:35:04 PM: info       at parse (<anonymous>)
Dec 23, 02:35:04 PM: info       at packageData (deno:ext/fetch/22_body.js:359:16)
Dec 23, 02:35:04 PM: info       at consumeBody (deno:ext/fetch/22_body.js:236:14)
Dec 23, 02:35:04 PM: info       at async lookupPlaylist (file:///root/netlify/edge-functions/utils/lookup-playlist-data.js:2:24)
Dec 23, 02:35:04 PM: info       at async findPlaylistsForGenre (file:///root/netlify/edge-functions/utils/find-playlists-for-genre.js:13:29)
Dec 23, 02:35:04 PM: info       at async Promise.all (index 2)
```

Rather than getting all the way to looking up the playlist, it should do this check earlier. Maybe ASAP when the app loads. It could just load a playlist and check if it's a 200 response.

And if it fails, it should have a nice message to say that it looks like the email address you used is not registered yet. Instructions for finding your account email address, and to contact Larry.

I could potentially make a fake Spotify account for testing this.

**Comment by larryhudson** [comment]
I'm really pleased with how this is resolved. This should make it much clearer for people who have given up. The error was bugging me!

Screenshot of the error that comes up when you are not registered:

<img width="983" alt="Screenshot with error message" src="https://user-images.githubusercontent.com/10627494/209412307-29c9b2f1-dc4f-4f38-ae97-e228d6938029.png">
